branches:
  only:
  - master
language: node_js
node_js:
  - "0.10"
install:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
before_script:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/webf-zone/webf.git"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis-ci"
script:
  - gulp release
after_success: bash deploy.sh
env:
  global:
  - secure:  "p1qg6/rnz4OHNHkY1YL6Pn9T7iT6RDMa3gfnDWSu6x1wQY36EJ/Ba9/lR5cfCgLzMtEJNAg2+wpV2AIdLnzWbEuYMe7IEYSywyAj1XCOqdnK2TXQj49sK60dXcblemsMpV2iZ9Sl2CABsQq2D8BQfwaB9l/Yibx4iL4PsxI1n90Qs9e0VK8vuwOtL7OKEDzc+H9iYXUaqrHdvaDGYMJXyX1AgVChTovkuvgIWMn72nGcGuxklQWni8Ay1HihipJ3UNUzEWwwWra5iCXTo4Jk9LX4IMFTREsNQd5bTnJv8vcU0w1cCvzIinouIo9N0MiqqkNU0YGcip2QHnNVk2KioLnC2FGaW4vDH0B9f6u4+go22zeNdoobpSvujPF6GUg+0OXX51O6V47ZvTdXhUMjCbmcDoawYYwzU35EWu9EA1o86ApjogUtNdVhF/I4lNM/nHTYsCoTx33exytXbomij10WfSl4tNpfFgmg2j/nEFGRoVDMzdOP080oF+j/R6XF0dlve49kG+reYymB1ya550Dfm469yrB9lY/2z83fMb06lcf+7+kgRnDipcGKPpgNN3Uv1/Hq+Lv06cOcKEKIWIK9zvBZWwdEvwZw/mYTwmMNjT94B/PtzQcR2OcvJ0Tbx4mZNVaeX5t+fsPs+9D+ebYZnpmXp8gXNphwgAvprIk="
  - secure: "OWAB6nVXi//Cz/a10n5QT/VkFGaE/7hXSE94jPUE8Ag6HFK+lj4L8o0FV4FpJMMTwtFqsydI4snKOMoeQNBq2bLganQLSG/JlUQOroZhMQUESNuxbpZFHT/pN6N2wgBGMphSvs3Wd9882f/OLpsds8T3/2fiRjd2fnx93Izsx/fVNa9D1PkKCETNFcYsnTXYFL+GalNn/GGw80SnTt2C7sdVUZ08vjkvFt3jN2mdaa5YEzPZ+RCTT8i14UJjyNOyzxk4SB3i2uVXY0T9X7ViYStZoPCMVeBQpAIQLnG5Z0KeiV9G4+ST0jZCx+Mj85aXkmxks8AdAkYkzgDN9EmrnDJU6Vlgw9aRYJMQXlPgHSfpQLxgm2B28X4xQQBFv4qEhQfyFj43Cg/sJgVRFCkfheAG/a9vVgFveBiazraBYX2f2hf2oM3idJoAjUm2QWYmRkBGvOPbbWRPgCWxdeiKCCqaYeuMm46SMpnsTVzFlwL515zCvRemDgiaJ2+Hf3iELyyUtZMTH22l/T5lL7wHzjPNiZ9pG0uCfkxU5LpgyKx9/s203KUIrl8NDez6SrRRla0ix6a15u72GToinB1zrmuta1HUkrIlh6PnqxXyq39qIKxK6PDK951WM8t+v/IlVpgiQWgQqnTlISkMSd542QC8dtk7fElkwYeABajBoXQ="