tags:
    baseUrl: /blog/tags/

taxonomies:
    Regions:
        Asia:
            India:
                North: false
                South: false
            China:
                North: false
            Singapore: false
        Europe:
            UK:
                England: ""
                Wales: false
                Scotland: false
            Germany: false
